(()=>{"use strict";
const SB=window.ieisSupabase,APP=window.IEIS_CONFIG.siteUrl,P=window.IEIS_PASSAGES||[];
const S={user:null,profile:null,screen:"home",mode:"login",test:null,history:[]};
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const words=x=>(String(x||"").trim().match(/\S+/g)||[]).length;
const date=x=>x?new Date(x).toLocaleString():"—";
function msg(t,c=""){let e=document.querySelector("#msg");if(e){e.textContent=t;e.className="msg "+c}}
function layout(c){return `<header><a href="#" onclick="home();return false"><img src="assets/ieis-logo.png"></a>${S.user?`<div>${esc(S.profile?.email||S.user.email)} <button class="dark" onclick="logout()">Sign out</button></div>`:""}</header>${c}`}
function home(){return layout(`<main class="wrap"><section class="hero"><img src="assets/ieis-logo.png"><div><small>IEIS.IO · ONLINE EXAMINATION</small><h1>IELTS Academic<br><em>Reading & Writing</em></h1><p>Professional computer-based practice with secure accounts, timed examinations, automatic Reading marking and staff results.</p><button onclick="auth('login')">Student / Staff Sign in</button> <button class="outline" onclick="auth('register')">Create Student Account</button></div></section><div class="stats"><div><b>1,000</b><span>Original passages</span></div><div><b>60 min</b><span>Reading</span></div><div><b>40</b><span>Questions</span></div><div><b>60 min</b><span>Writing</span></div></div><div class="cards"><article><b>READING</b><h2>Academic Reading</h2><p>3 passages, 40 questions, 60 minutes and automatic practice scoring.</p></article><article><b>WRITING</b><h2>Academic Writing</h2><p>Task 1 + Task 2 in 60 minutes with live word counts and examiner criteria guidance.</p></article><article><b>ACCOUNTS</b><h2>Student & Staff</h2><p>Supabase authentication, persistent sessions, candidate records and protected staff access.</p></article></div><div class="note">IEIS is an independent practice platform using the published IELTS format. It is not an official IELTS/British Council/IDP/Cambridge test platform.</div></main>`)}
function auth(m){S.screen="auth";S.mode=m;render()}
function authView(){let r=S.mode==="register";return layout(`<main class="auth"><div class="box"><img src="assets/ieis-logo.png"><small>${r?"NEW CANDIDATE":"SECURE ACCESS"}</small><h1>${r?"Create student account":"Welcome back"}</h1>${r?`<label>Full name<input id="name" autocomplete="name"></label>`:""}<label>Email<input id="email" type="email" autocomplete="email"></label><label>Password<input id="pass" type="password" autocomplete="${r?"new-password":"current-password"}"></label>${r?`<label>Confirm password<input id="pass2" type="password"></label>`:""}<button id="authBtn" onclick="${r?"register()":"login()"}">${r?"Create account":"Sign in"}</button>${!r?`<button class="link" onclick="resetView()">Forgot password?</button>`:""}<div id="msg" class="msg"></div><button class="outline full" onclick="auth('${r?"login":"register"}')">${r?"Back to sign in":"Create student account"}</button></div></main>`)}
async function register(){let n=document.querySelector("#name").value.trim(),e=document.querySelector("#email").value.trim().toLowerCase(),p=document.querySelector("#pass").value,p2=document.querySelector("#pass2").value;if(!n||!e||p.length<8||p!==p2){msg("Enter a name, valid email, 8+ character password and matching confirmation.","error");return}let b=document.querySelector("#authBtn");b.disabled=true;let {data,error}=await SB.auth.signUp({email:e,password:p,options:{data:{full_name:n},emailRedirectTo:APP}});b.disabled=false;if(error){msg(error.message.includes("rate")?"Supabase email rate limit reached. Wait for the countdown before requesting another email.":error.message,"error");return}if(data.session){await identity(data.user);S.screen=S.profile?.role==="staff"?"staff":"student";render()}else msg("Account created. Check your email, confirm it, then return to IEIS and sign in.","ok")}
async function login(){let e=document.querySelector("#email").value.trim().toLowerCase(),p=document.querySelector("#pass").value;if(!e||!p){msg("Enter email and password.","error");return}let b=document.querySelector("#authBtn");b.disabled=true;let {data,error}=await SB.auth.signInWithPassword({email:e,password:p});b.disabled=false;if(error){msg(error.message,"error");return}await identity(data.user);S.screen=S.profile?.role==="staff"?"staff":"student";render()}
async function identity(u){S.user=u;let {data}=await SB.from("profiles").select("id,full_name,email,role,created_at").eq("id",u.id).single();S.profile=data||{id:u.id,email:u.email,full_name:u.user_metadata?.full_name||"",role:"student"}}
function resetView(){S.screen="reset";render()}
function reset(){return layout(`<main class="auth"><div class="box"><img src="assets/ieis-logo.png"><small>ACCOUNT RECOVERY</small><h1>Reset password</h1><label>Email<input id="resetEmail" type="email"></label><button onclick="sendReset()">Send reset link</button><div id="msg" class="msg"></div><button class="outline full" onclick="auth('login')">Back to sign in</button></div></main>`)}
async function sendReset(){let e=document.querySelector("#resetEmail").value.trim().toLowerCase(),m=document.querySelector("#msg");let {error}=await SB.auth.resetPasswordForEmail(e,{redirectTo:APP});m.textContent=error?error.message:"If an account exists, a reset email has been sent.";m.className="msg "+(error?"error":"ok")}
function student(){return layout(`<main class="wrap"><small>CANDIDATE PORTAL</small><h1>Student Dashboard</h1><p>Welcome, <b>${esc(S.profile?.full_name||S.user.email)}</b> · ${esc(S.profile?.email||S.user.email)}</p><div class="stats"><div><b>1,000</b><span>Passages</span></div><div><b>60 min</b><span>Reading</span></div><div><b>40</b><span>Questions</span></div><div><b>60 min</b><span>Writing</span></div></div><div class="cards"><article><b>READING</b><h2>Academic Reading</h2><p>Three passages, 40 questions and a real 60-minute countdown.</p><button onclick="startReading()">Begin Reading</button></article><article><b>WRITING</b><h2>Academic Writing</h2><p>Task 1 minimum 150 words; Task 2 minimum 250 words.</p><button onclick="startWriting()">Begin Writing</button></article><article><b>HISTORY</b><h2>My Attempts</h2><p>Review your completed examinations.</p><button class="outline" onclick="history()">View history</button></article></div><div id="extra"></div></main>`)}
function startReading(){if(P.length!==1000){alert("Reading library error: expected exactly 1,000 passages.");return}S.test={kind:"reading",ps:P.slice().sort(()=>Math.random()-.5).slice(0,3),page:0,a:{},end:Date.now()+3600000};S.screen="reading";render();timer()}
function startWriting(){S.test={kind:"writing",t1:"",t2:"",end:Date.now()+3600000};S.screen="writing";render();timer()}
function timer(){clearInterval(window.ieisTimer);window.ieisTimer=setInterval(()=>{let l=Math.max(0,S.test.end-Date.now()),e=document.querySelector("#timer");if(e){let x=Math.ceil(l/1000),m=Math.floor(x/60),s=x%60;e.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;e.classList.toggle("danger",x<=300)}if(l<=0){clearInterval(window.ieisTimer);finish(true)}},250)}
function qhtml(q,n){let v=S.test.a[n]||"";if(q.type==="mcq")return `<div class="q"><b>${n}. ${esc(q.prompt)}</b>${q.options.map(o=>`<label><input type="radio" name="q${n}" value="${esc(o)}" ${v===o?"checked":""}> ${esc(o)}</label>`).join("")}</div>`;return `<div class="q"><b>${n}. ${esc(q.prompt)}</b><input id="q${n}" value="${esc(v)}"></div>`}
function savePage(){let i=S.test.page,start=i===0?1:i===1?14:27,count=i===2?14:13;for(let n=start;n<start+count;n++){let r=document.querySelector(`input[name=q${n}]:checked`),t=document.querySelector("#q"+n);if(r)S.test.a[n]=r.value;else if(t)S.test.a[n]=t.value.trim()}}
function reading(){let t=S.test,p=t.ps[t.page],start=t.page===0?1:t.page===1?14:27,count=t.page===2?14:13;return `<main class="exam"><div class="bar"><b>IEIS.IO · IELTS Academic Reading</b><span>Passage ${t.page+1}/3</span><strong id="timer">60:00</strong></div><div class="examgrid"><section class="passage"><small>READING PASSAGE ${t.page+1}</small><h1>${esc(p.title)}</h1><p>${esc(p.field||p.topic||"Academic text")}</p><article>${esc(p.passage)}</article></section><section class="questions"><small>QUESTIONS ${start}–${start+count-1}</small>${p.questions.slice(0,count).map((q,i)=>qhtml(q,start+i)).join("")}</section></div><div class="actions"><button class="outline" onclick="exitExam()">Exit</button>${t.page?`<button class="outline" onclick="savePage();S.test.page--;render();timer()">Previous</button>`:""}${t.page<2?`<button onclick="savePage();S.test.page++;render();timer()">Next passage</button>`:`<button onclick="savePage();finish(false)">Submit Reading</button>`}</div></main>`}
function writing(){let t=S.test;return `<main class="exam"><div class="bar"><b>IEIS.IO · IELTS Academic Writing</b><span>Task 1 + Task 2</span><strong id="timer">60:00</strong></div><div class="write"><div class="note"><b>60 minutes total.</b> Task 1: at least 150 words, about 20 minutes. Task 2: at least 250 words, about 40 minutes. Task 2 contributes twice as much as Task 1.</div><section><small>TASK 1</small><h2>Summarise the information by selecting and reporting the main features, and make comparisons where relevant.</h2><p>The table shows average hours per week that students at a college spent on five study activities in 2012 and 2022.</p><table><tr><th>Activity</th><th>2012</th><th>2022</th></tr><tr><td>Independent reading</td><td>6</td><td>9</td></tr><tr><td>Lectures</td><td>8</td><td>7</td></tr><tr><td>Group study</td><td>3</td><td>5</td></tr><tr><td>Laboratory work</td><td>4</td><td>6</td></tr><tr><td>Online practice</td><td>2</td><td>8</td></tr></table><textarea id="t1" placeholder="Write at least 150 words">${esc(t.t1)}</textarea><p>Words: <b id="w1">${words(t.t1)}</b></p></section><section><small>TASK 2</small><h2>Some people believe that universities should focus mainly on subjects that lead directly to employment. Others believe universities should offer a broad range of subjects. Discuss both views and give your own opinion.</h2><textarea id="t2" placeholder="Write at least 250 words">${esc(t.t2)}</textarea><p>Words: <b id="w2">${words(t.t2)}</b></p></section><div class="actions"><button class="outline" onclick="exitExam()">Exit</button><button onclick="finish(false)">Submit Writing</button></div></div></main>`}
function attachWrite(){for(let id of["t1","t2"]){let e=document.querySelector("#"+id);e.oninput=()=>{S.test[id==="t1"?"t1":"t2"]=e.value;document.querySelector("#"+(id==="t1"?"w1":"w2")).textContent=words(e.value)}}}
async function finish(auto){if(S.test.kind==="reading")savePage();else{S.test.t1=document.querySelector("#t1")?.value||"";S.test.t2=document.querySelector("#t2")?.value||""}clearInterval(window.ieisTimer);if(S.test.kind==="reading"){let score=0,n=1;S.test.ps.forEach((p,i)=>{let c=i===2?14:13;for(let j=0;j<c;j++,n++)if(String(S.test.a[n]||"").trim().toLowerCase()===String(p.questions[j].answer||"").trim().toLowerCase())score++});let band=bandOf(score);await save({kind:"reading",score,band,answers:S.test.a,auto});S.test.result={kind:"reading",score,band,auto}}else{let w1=words(S.test.t1),w2=words(S.test.t2);await save({kind:"writing",words1:w1,words2:w2,task1:S.test.t1,task2:S.test.t2,auto});S.test.result={kind:"writing",w1,w2,auto}}S.screen="result";render()}
function bandOf(s){return s>=39?"9.0":s>=37?"8.5":s>=35?"8.0":s>=33?"7.5":s>=30?"7.0":s>=27?"6.5":s>=23?"6.0":s>=19?"5.5":s>=15?"5.0":s>=13?"4.5":s>=10?"4.0":s>=8?"3.5":s>=6?"3.0":s>=4?"2.5":"2.0"}
async function save(x){let {error}=await SB.from("attempts").insert({user_id:S.user.id,...x});if(error)console.error(error)}
function result(){let r=S.test.result;return layout(`<main class="wrap narrow"><section class="result"><small>SUBMISSION COMPLETE</small><h1>${r.kind==="reading"?"Reading result":"Writing submission"}</h1>${r.kind==="reading"?`<div class="score">${r.score}<small>/40</small></div><h2>Practice band estimate: ${r.band}</h2><p>Reading conversion is a practice estimate; official conversions can vary by test version.</p>`:`<h2>Writing submitted</h2><p>Task 1: <b>${r.w1}</b> words · Task 2: <b>${r.w2}</b> words.</p><p>Writing requires assessment against Task Achievement/Response, Coherence and Cohesion, Lexical Resource, and Grammatical Range and Accuracy. This system does not falsely present automated scoring as an official IELTS examiner score.</p>`}${r.auto?`<div class="note">The 60-minute timer reached zero; the attempt was submitted automatically.</div>`:""}<button onclick="S.screen='student';render()">Back to dashboard</button></section></main>`)}
async function history(){let {data}=await SB.from("attempts").select("kind,score,band,words1,words2,created_at").eq("user_id",S.user.id).order("created_at",{ascending:false});S.history=data||[];let e=document.querySelector("#extra");e.innerHTML=`<section class="card"><h2>My examination history</h2><table><tr><th>Date</th><th>Module</th><th>Score</th><th>Band</th></tr>${S.history.map(a=>`<tr><td>${esc(date(a.created_at))}</td><td>${esc(a.kind)}</td><td>${a.score==null?"—":a.score+"/40"}</td><td>${esc(a.band||"Human assessment")}</td></tr>`).join("")||"<tr><td colspan=4>No attempts yet.</td></tr>"}</table></section>`}
async function staff(){if(S.profile?.role!=="staff"){S.screen="student";render();return}let [u,a]=await Promise.all([SB.from("profiles").select("id,full_name,email,created_at").eq("role","student").order("created_at",{ascending:false}),SB.from("attempts").select("user_id,kind,score,band,created_at").order("created_at",{ascending:false}).limit(500)]);let map={};(u.data||[]).forEach(x=>map[x.id]=x);return layout(`<main class="wrap"><small>AUTHORIZED STAFF</small><h1>Staff Dashboard</h1><div class="stats"><div><b>${u.data?.length||0}</b><span>Students</span></div><div><b>${a.data?.length||0}</b><span>Attempts</span></div><div><b>1,000</b><span>Passages</span></div><div><b>40</b><span>Questions</span></div></div><section class="card"><h2>Registered students</h2><table><tr><th>Name</th><th>Email</th><th>Registered</th></tr>${(u.data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td>${esc(date(x.created_at))}</td></tr>`).join("")||"<tr><td colspan=3>No students.</td></tr>"}</table></section><section class="card"><h2>Recent attempts</h2><table><tr><th>Candidate</th><th>Email</th><th>Module</th><th>Score</th><th>Band</th><th>Date</th></tr>${(a.data||[]).map(x=>`<tr><td>${esc(map[x.user_id]?.full_name||"—")}</td><td>${esc(map[x.user_id]?.email||"—")}</td><td>${esc(x.kind)}</td><td>${x.score==null?"—":x.score+"/40"}</td><td>${esc(x.band||"Human assessment")}</td><td>${esc(date(x.created_at))}</td></tr>`).join("")||"<tr><td colspan=6>No attempts.</td></tr>"}</table></section></main>`)}
async function logout(){clearInterval(window.ieisTimer);await SB.auth.signOut();S.user=null;S.profile=null;S.screen="home";render()}
function exitExam(){if(confirm("Exit this examination? Unsaved answers will be lost.")){clearInterval(window.ieisTimer);S.test=null;S.screen="student";render()}}
function render(){let a=document.querySelector("#app");if(S.screen==="home")a.innerHTML=home();else if(S.screen==="auth")a.innerHTML=authView();else if(S.screen==="reset")a.innerHTML=reset();else if(S.screen==="student")a.innerHTML=student();else if(S.screen==="reading")a.innerHTML=reading();else if(S.screen==="writing"){a.innerHTML=writing();attachWrite()}else if(S.screen==="result")a.innerHTML=result();else if(S.screen==="staff"){a.innerHTML=`<main class=wrap><div class=card>Loading…</div></main>`;staff().then(x=>a.innerHTML=x)}}
async function boot(){let {data}=await SB.auth.getSession();if(data.session){await identity(data.session.user);S.screen=S.profile?.role==="staff"?"staff":"student"}SB.auth.onAuthStateChange(async(_,session)=>{if(session&&!S.user){await identity(session.user);S.screen=S.profile?.role==="staff"?"staff":"student";render()}if(!session&&S.user){S.user=null;S.profile=null;S.screen="home";render()}});render()}
window.home=()=>{S.screen=S.user?(S.profile?.role==="staff"?"staff":"student"):"home";render()};window.auth=auth;window.register=register;window.login=login;window.resetView=resetView;window.sendReset=sendReset;window.startReading=startReading;window.startWriting=startWriting;window.finish=finish;window.exitExam=exitExam;window.logout=logout;window.history=history;
boot();
})();